jitsi:
  publicURL: "meet.minikube.loc"

  websockets:
    colibri:
      enabled: false
    xmpp:
      enabled: true

  web:
    replicaCount: 1
    image:
      repository: jitsi/web
      tag: "stable-10184"

    custom:
      configs:
        _custom_interface_config_js: ""
        _custom_config_js: |
          // Deeplinking
          config.deeplinking = {
            disabled: true,
          };

          // Lobby
          config.lobby = {
            autoKnock: true,
            enableChat: true,
          };

          // Lobby password
          config.securityUi = {
            disableLobbyPassword: true,
          };

    extraEnvs:
      DYNAMIC_BRANDING_URL: "/static/branding.json"
      ENABLE_PREJOIN_PAGE: "true"
      HIDE_PREJOIN_DISPLAY_NAME: "true"
      TOKEN_AUTH_URL: "https://meet.minikube.loc/static/auth.html?state={state}"

    extraVolumes:
      - name: "volume-jitsi-web"
        configMap:
          name: "cm-jitsi-web"
          items:
            - key: "auth.html"
              path: "auth.html"
            - key: "branding.json"
              path: "branding.json"

    extraVolumeMounts:
      - name: "volume-jitsi-web"
        subPath: "auth.html"
        mountPath: "/usr/share/jitsi-meet/static/auth.html"
      - name: "volume-jitsi-web"
        subPath: "branding.json"
        mountPath: "/usr/share/jitsi-meet/static/branding.json"

    ingress:
      enabled: true
      hosts:
        - host: meet.minikube.loc
          paths: ["/"]

  jicofo:
    replicaCount: 1
    image:
      repository: jitsi/jicofo
      tag: "stable-10184"
    extraEnvs:
      ENABLE_AUTO_OWNER: "false"
      JICOFO_ENABLE_AUTH: "false"

  jvb:
    replicaCount: 2
    image:
      repository: jitsi/jvb
      tag: "stable-10184"

    publicIPs:
      - 172.18.18.21

    UDPPort: 30011
    nodePort: 30011
    service:
      type: NodePort

    extraEnvs:
      JVB_DISABLE_STUN: "true"

  octo:
    enabled: true

  prosody:
    image:
      repository: jitsi/prosody
      tag: "stable-10184"
    extraEnvs:
      - name: "AUTH_TYPE"
        value: "jwt"
      - name: "ENABLE_AUTH"
        value: "true"
      - name: "XMPP_MODULES"
        value: "persistent_lobby"
      - name: "XMPP_MUC_MODULES"
        value: "lobby_autostart,token_affiliation,token_lobby_bypass,token_lobby_bypass_for_initiator,lobby_deactivate"
    secretEnvs:
      JWT_APP_ID: "myappid"
      JWT_APP_SECRET: "myappsecret"
